config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # resource :cart, only: [:show] do
  #   post 'add', on: :member
  #   post 'remove', on: :member
  # end
  get 'cart', to: 'cart#show'
  post 'cart/add'
  post 'cart/remove'

  
  resources :connections, only: [] do
    member do
      post 'follow', 'unfollow', 'accept', 'decline', 'cancel'
    end
  end

  resources :users, only: [:show] do
    resources :posts, :products
  end

  resources :posts do
    resources :likes, module: :posts, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end

  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :orders
    has_many :products, through: :orders

    def total
        orders.to_a.sum { |order| order.total }
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :record, polymorphic: true, counter_cache: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total
    product.price * quantity
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :photo
  has_many :comments
  has_many :likes, as: :record
  belongs_to :user

  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 10 }

  def like_by?(user)
    likes.where(user:).any?
  end

  def like(user)
    likes.where(user:).first_or_create
  end

  def unlike(user)
    likes.where(user:).destroy_all
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :orders
  has_many :carts, through: :orders

  has_one_attached :image
  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts
  has_many :products
  has_one_attached :profile_photo
  has_many :likes
 
  
  followability

  validates :username, presence: true, uniqueness: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  def unfollow(user)
    followerable_relationships.where(followable_id: user.id).destroy_all
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @render_cart = false
    
  end

  def add
    @product = Product.find_by(id: params[:id])
    quantity = params[:quantity].to_i
    current_order = @cart.orders.find_by(product_id: @product.id)
    if current_order && quantity > 0
      current_order.update(quantity:)
    elsif quantity <= 0
      current_order.destroy
    else
      @cart.orders.create(product: @product, quantity:)

    end



  end

  def remove
    Order.find_by(id: params[:id]).destroy
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace('cart',
                                                  partial: 'cart/cart',
                                                  locals: { cart: @cart })
      end
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: [:create]
  before_action :set_comment, only: [:edit, :update, :destroy]

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to post_path(@post), notice: 'Comment was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # Define edit, update, and destroy actions here if needed

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @welcome = 'Introducing the ExquisiteEvo Boomer - Unleash the Power of Elegance'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_user
  before_action :set_post, only: %i[edit update destroy]
  before_action :authenticate_user!

  def index
    @posts = Post.all
    @users = User.all
    @post = current_user.posts.build
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @other_posts = @user.posts.where.not(id: @post.id)
  end

  def new
    @post = @user.posts.build
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to user_post_path(current_user, @post), notice: 'Post was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to user_post_path(@user, @post), notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:user_id]) if params[:user_id]
  end

  def post_params
    params.require(:post).permit(:title, :description, :photo)
  end

  def set_post
    @post = @user.posts.find(params[:id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_product, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: [:add_to_cart]
  before_action :set_user

  def index
    @products = Product.all
  end

  def show
    @comment = Comment.new
  end

  def new
    @product = @user.products.new
  end

  def create
    @product = @user.products.build(product_params)

    if @product.save
      redirect_to user_product_path(@user, @product), notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully destroyed.'
  end



  private

  def set_product
    @product = Product.find(params[:id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def product_params
    params.require(:product).permit(:title, :description, :price, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
#   before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/connections_helper.rb
module ConnectionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/cart/_cart.html.erb
<%= turbo_frame_tag "cart" do %>
  <h1>Cart</h1>
  <% if @cart.orders.count > 0 %>
    <%= render "cart/order" %>
    <p>Total: <%= @cart.total %></p>
  <% else %>
    <p>Your cart is empty</p>
  <% end %>
<% end %>

app/views/cart/_orders.html.erb
<div class="card border p-5" style="width: 80%; margin-left:10%; background-color:#FFFFFF;">
  <div class="border-b" style="width: 80%;">
    Cart ( <%= @cart.orders.count %> )
  </div>

  <div class="flex justify-around" >
    <div style="width: 80%;">
      <% @cart.orders.each do |order| %>
        <% product = order.product %>
        <div class="" id="<%= "cart-#{product.id}" %>">
          <div class="border mt-2 p-5 " style="width: 80%;">
            <div class="flex-col content-between">
              <div class="flex justify-between">
                <div class="left flex">
                  <div style="width: 200px;">
                    <%= image_tag product.image, class:"" if product.image.attached?  %>
                  </div>
                  <div class="ml-4">
                    <p class="font-bold"><%= product.title %></p> 
                    <p><%= product.description %></p>
                  </div>
                </div>
                <div class="right">
                  <%= number_to_currency(product.price)%>
                </div>
              </div>
              <div class="mt-20 flex justify-between" style="width: 100%;">
                <div>
                  <%= form_tag(cart_remove_path, method: :delete) do %>
                    <%= hidden_field_tag :id, order.id %>
                    <%= button_tag(type: 'submit', class: 'icon-button') do %>
                      <%= icon('fa-solid', 'trash', class: 'icon') %>
                    <% end %>
                  <% end %>
                </div>

                <div class="flex items-center">
                  <div>
                    <%= form_tag(cart_remove_path, method: :delete) do %>
                      <%= hidden_field_tag :id, product.id %>
                      <%= button_tag(type: 'submit', class: 'icon-button') do %>
                        <%= icon('fa-solid', 'minus', class: 'icon') %>
                      <% end %>
                    <% end %>
                  </div>
                  <div class="px-2">
                    <%= order.quantity %>
                  </div>
                  <div>
                    <%= form_tag(cart_add_path, method: :post) do %>
                      <%= hidden_field_tag :id, product.id %>
                      <%= button_tag(type: 'submit', class: 'icon-button') do %>
                        <%= icon('fa-solid', 'plus', class: 'icon') %>
                      <% end %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div class="border p-5 mt-2" style="width: 20%; height:250px; ">
      <div class="border-b">
        <p class="font-medium">Order Summary</p>
      </div>

      <div class="flex justify-between mt-5">
        <div>
          <p class="font-bold">Total:</p>
        </div>
        <div>
          <%= number_to_currency(@cart.total) %>
        </div>
      </div>
      <div class="flex justify-between mt-5">
        <div>
          <p class="font-bold">Shipping:</p>
        </div>
        <div>
          <%= number_to_currency(0) %>
        </div>
      </div>
      <div class="flex justify-between mt-5">
        <div>
          <p class="font-bold">Tax:</p>
        </div>
        <div>
          <%= number_to_currency(0) %>
        </div>
      </div>
      <div class="border-b py-1">
      </div>
      <div class="flex justify-between mt-5">
        <div>
          <p class="font-bold">Total:</p>
        </div>
        <div>
          <%= number_to_currency(@cart.total) %>
        </div>
      </div>
      <div class="mt-5">
        <%= link_to "Checkout", new_user_product_path(@cart), class:"text-white text-sm font-light p-2" %>
      </div>
    </div>

  </div>
</div>

app/views/cart/show.html.erb
<div class="mt-20">
<%= turbo_frame_tag "cart" do %>

  <% if @cart.orders.count > 0 %>
    <%= render "cart/orders" %>
  <% else %>
    <p>Your cart is empty</p>
  <% end %>
<% end %>

</div>

app/views/comments/_comment.html.erb
<div class="comment" style="height: 20%;">
  <div class="flex p-5 my-5">
    <div class="">
        <%= image_tag comment.user.profile_photo, class: "w-10 h-10 rounded-full" if comment.user.profile_photo.attached? %>
    </div>
    <div class="flex-col ml-2">
        <span class="text-sm font-bold"><%= comment.user.username %></span>
        <span class="text-sm ml-3"><%= comment.body %> </span>
       <p class="text-xs text-slate-400"><%= time_ago_in_words(comment.created_at).gsub("minutes", "m").gsub("hours", "h") %> ago</p>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [ @post, @post.comments.build ], html: { class: '' } do |form| %>

<div class="w-full">
  <div class="">
    <%= form.text_area :body, class: "custom-text-area", placeholder:"Add comment" %>
  </div>
</div>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    const commentBody = document.getElementById('comment_body');
    commentBody.addEventListener('keydown', function(event) {
      if (event.key === 'Enter' && !event.shiftKey) {
        event.preventDefault(); // Prevent new line
        commentBody.form.submit(); // Submit the form
      }
    });
  });
</script>
<% end %>

app/views/products/_form.html.erb
<%= form_with(model: [@user, @product], local: true, html: { multipart: true }) do |form| %>
    <div class="mx-10 my-5">
        <div class="flex justify-between items-center" style="width: 90%;">
            <div class="flex-col" style="">
            <%= form.label :title, class:'text-sm font-bold' %>
            </div>
            <div class="">
            <%= form.text_field :title, class:"input" %>
            </div>
        </div>
    </div>

    <div class="mx-10 my-5">
        <div class="flex justify-between items-center" style="width: 90%;">
        <div class="" style="">
            <%= form.label :description, class:"font-bold text-sm" %>
        </div>
        <div class="">
            <%= form.text_area :description,  class:"input" %>
        </div>
        </div>
    </div>

    <div class="mx-10 my-5">
        <div class="flex justify-between items-center" style="width: 90%;">
        <div class="flex-col" style="">
            <%= form.label :price,class:"font-bold text-sm"  %>
        </div>
        <div class="">
            <%= form.number_field :price, step: '0.01',class:"input" %>
        </div>
        </div>
    </div>
    <div class="mx-10 my-5">
        <div class="flex justify-between items-center" style="width: 90%;">
        <div class="" style="">
            <%= form.label :image, class:'text-sm text-slate-600 font-bold' %>
        </div>
        <div class="">
            <%= form.file_field :image , class: 'input ' %> 
        </div>
        </div>
    </div>
    <div class="mx-10 my-5">
        <div class="flex justify-between items-center" style="width: 100%;">
        <div class="mt-10" style="width:100%; background-color:#003049; text-align:center;">
            <%= form.submit "Create", class:"text-white text-sm font-light p-2" %>
        </div>
        </div>
    </div>
<% end %>

app/views/products/_sidebar.html.erb
  <div class=" w-1/6 left-hand-side border-r-2">
      <div class="flex-col h-full justify-between ">
      <div class="mx-10 my-10" style="color: #003049;">
        <%= link_to 'Boomer', posts_path, class:"text-2xl font-bold tracking-widest" %>
      </div>
      <div class="flex-col justify-between h-3/5 mx-10 my-10" style="">
        <div class="h-1/6 flex items-center">
           <%= icon('fa-solid', 'house', class: 'icon')%>
           <%= link_to 'Home', posts_path, class:"text-sm ml-3" %>
        </div>
        <div class="h-1/6 flex items-center">
          <%= icon('fa-solid', 'shop', class: 'icon')%>
          <%= link_to 'Sell', new_user_product_path(current_user), class:"text-sm ml-3" %>
        </div>
        <div class="h-1/6 flex items-center">
          <%= icon('fa-solid', 'tag', class: 'icon')%>
            <%= link_to 'Buy', user_products_path, class:"text-sm ml-3" %>
        </div>

        <div class="flex h-1/6 items-center">
          <%= image_tag current_user.profile_photo, class: "h-8 w-8 rounded-full" if current_user.profile_photo.attached? %>
          <%= link_to 'Profile', user_path(current_user), class:'text-sm ml-3' %>
        </div>
      </div>
      <div class="w-full text-center p-2 flex justify-around" style="position:absolute; top:95%">
          <%= icon('fa-solid','right-from-bracket', class: 'icon')%>
          <%= button_to "Log Out", destroy_user_session_path, method: :delete, class:"ml-3 font-sm" %>
      </div>
    </div>
  </div>

app/views/products/index.html.erb
<div class="flex justify-between ">
 <%= render partial: 'sidebar' %>
  <div class="flex w-5/6 justify-between main-content">
        <div class="flex-col mt-20" style="margin-left: 25%; height: 47%; width:100%;">
        <h1>Today's picks</h1>
        <% if @products.any? %>
          <div class="flex flex-wrap justify-between mt-20" style="width: 850px; height:100%;">
              <% @products.each do |product| %>
              
                <div class="border" style="width:280px; height:300px">
                  <%= image_tag product.image, class: "h-3/5 w-full border-b-4"  if product.image.attached? %>
                  <div class="my-2 p-2 ">
                    <h1 class="font-bold text-sm"><%= product.title %></h1>
                    <p class="font-light text-sm"><%= product.description %></p>
                    <p><%= number_to_currency(product.price) %></p>
                    <div class="border-x flex justify-between mt-2">
                      <%= link_to "View Details", user_product_path(@user, product), class:"font-light text-xs border p-1" %>
                      

                    </div>
                  </div>
                </div>
              
              <% end %>
          </div>
        <% else %>
            <p>No other products from <%= @user.username %> yet.</p>
        <% end %>
        </div>


      <div class="w-1/4 flex justify-self-center" style="margin-top: 2%;">
        <%= link_to cart_path do %>
          <div class="flex">
            <%= icon('fa-solid', 'cart-shopping', class: 'icon cart-icon')%>
            <p class=" px-2 text-sm font-light">Cart</p>
            <div style="position: absolute; top:2.8%; right:11.5%; z-index:2222;  background-color:#FFD700; height:10px; width:10px; border-radius:50%;">
              <p class="text-xs text-center font-bold" style="font-size:8px; color:#333333; position:absolute; left:22%; top:-20%;"><%= @cart.orders.count %></p>
            </div>
          </div>
       <%end%>
      </div>
  </div>
</div>

app/views/products/new.html.erb
<!-- app/views/products/new.html.erb --> 
<div class="flex justify-between ">
 <%= render partial: 'sidebar' %>

  <div class="mx-10 my-10">
    <h1 class="font-bold text-2xl" style="color: #003049;">New Product</h1>
  </div>
  <div class="flex w-5/6 justify-between main-content">
    <div class="flex-col mt-20" style=" height: 100%; width:100%;">
      <div class="flex justify-between my-10">
        <div></div>
          <div class="border flex" style="width: 60%; height:100%">
            <div class="border" style="width: 30%;">
              <div class="flex-col items-center w-full border-b p-2" >
                <h1 class="font-bold text-center mt-10 text-2xl" style="color: #003049;">Boomer</h1>
                <p class="font-light text-center text-sm">New Product</p>
              </div>
              <div class="my-10">
                <p class="text-center"><%= link_to 'Back', user_products_path(@user), class:"font-light text-sm" %></p>
              </div>
            </div>
            <div class="">
              <div class="" style="width: 50%;">
                <div class="my-5 ml-5">
                  <h1 class="text-2xl font-semibold">Create Your Product</h1>
                </div>
                <div class="mx-10 ">
                  <div class="flex justify-between" style="width: 40%;">
                    <div class="rounded-full bg-slate-200" style="height: 30px; width:30px; ">
                      <%= image_tag current_user.profile_photo, class: "h-full w-full rounded-full" if current_user.profile_photo.attached? %>
                    </div>
                    <div class="">
                        <h1 class="font-bold ml-3.5"><%= current_user.username %></h1>
                      </div>
                    </div>

                </div>
              </div>

            <%= render 'form' %>
            </div>
          </div>
        <div></div>
      </div>
     
    </div>
  </div>
</div>

app/views/products/show.html.erb
<%= turbo_page_requires_reload %>
<div class="flex justify-between ">
 <%= render partial: 'sidebar' %>
  <div class="flex w-5/6 justify-between main-content">
     <div class="flex-col mt-20" style="margin-left: 25%; height: 47%; width:100%;">
         <div class="flex" style=" height: 100%; width:100%;">
            <div class="border p-4 " style="width:500px" >
                <div class="">
                    <%= image_tag @product.image, class:"showpost" if @product.image.attached?  %>
                  <div>
                      <h1 class="text-sm font-bold"><%= @product.title %></h1>
                      <p class="text-sm font-light"><%= @product.description %></p>
                      <p><%= number_to_currency(@product.price) %></p>
                  </div>
                </div>
                <div style="width: fit-content;">
                <%= form_with(url: cart_add_path(@product.id), local: true) do |form| %>
                  <%= form.hidden_field :id, value: @product.id %>
                  <%= form.number_field :quantity, value: 0, min: 1 %>
                  <%= form.submit "Add To Cart" %>
                <% end %>
                </div>
              </div>
              <div class="border" style="width:350px; height:92%">
              <div class="flex justify-between items-center border-b p-1">
                <div class="flex items-center ">
                  <%= image_tag @user.profile_photo, class: "w-9 h-9 rounded-full" if @user.profile_photo.attached? %>
                  <span class="text-sm font-bold ml-2"><%= @user.username %></span>
                </div>
                
                <% if @user.id == current_user.id %>
                  <%= turbo_frame_tag "post_modal" do %>
                    <%= link_to edit_user_product_path(user_id: @product.user, id: @product) do %>
                        <%= icon('fa-solid', 'ellipsis', class: 'icon')%>
                    <%end%>
                  <%end%>
                <% end %>
                

              </div>
              
               <div class="comment">

               </div>

              </div>
          </div>

          <div class="mt-10 border-b" style="width: 850px;"></div>
          <div class="mt-10 text-2xl"> <h2>Other Product by <%= @user.username %>:</h2></div>

          </div>


      <div class="w-1/4 justify-self-center text-center">
        <p class="text-xs font-light text-slate-300">Posted by: <%= link_to @user.username, user_path(@user) %></p>
        <p class="text-xs font-light text-slate-300">Posted on: <%= @product.created_at.strftime("%B %d, %Y") %></p>
      </div>
  </div>
</div>

app/views/users/_sidebar.html.erb
  <div class=" w-1/6 left-hand-side border-r-2">
      <div class="flex-col h-full justify-between ">
      <div class="mx-10 my-10", style="color: #003049;">
        <%= link_to 'Boomer', posts_path, class:"text-2xl font-bold tracking-widest" %>
      </div>
      <div class="flex-col justify-between h-3/5 mx-10 my-10" style="">
        <div class="h-1/6 flex items-center">
          <%= icon('fa-solid', 'pen-to-square', class: 'icon')%>
          <%= link_to "Create", new_user_post_path(current_user), class:"text-sm ml-3" %>
        </div>
        <div class="h-1/6 flex items-center">
           <%= icon('fa-solid', 'house', class: 'icon')%>
           <%= link_to 'Home', posts_path, class:"text-sm ml-3" %>
        </div>
        <div class="h-1/6 flex items-center">
          <%= icon('fa-solid', 'shop', class: 'icon')%>
          <p class="text-sm ml-3">Sell</p>
        </div>
        <div class="h-1/6 flex items-center">
          <%= icon('fa-solid', 'envelope', class: 'icon')%>
          <p class="text-sm ml-3">Messages</p>
          
        </div>
        <div class="flex h-1/6 items-center">
          <%= icon('fa-solid', 'heart', class: 'icon')%>
          <p class="text-sm ml-3">Notification</p>
        </div>
        <div class="flex h-1/6 items-center">
          <%= image_tag current_user.profile_photo, class: "h-8 w-8 rounded-full" if current_user.profile_photo.attached? %>
          <%= link_to 'Profile', user_path(current_user), class:'text-sm ml-3' %>
        </div>
      </div>
      <div class="w-full text-center p-2 flex justify-around" style="position:absolute; top:95%">
          <%= icon('fa-solid','right-from-bracket', class: 'icon')%>
          <%= button_to "Log Out", destroy_user_session_path, method: :delete, class:"ml-3 font-sm" %>
      </div>
    </div>
  </div>

app/views/users/index.html.erb
        
        <div class="flex-col" style="margin-top:10%; width:85%;">
          <% @users.each do |user| %>
            <div class="flex items-center ">
                <div class="rounded-full bg-slate-200 w-20 h-20">
                  <%= image_tag user.profile_photo, class: "h-full w-full rounded-full" if user.profile_photo.attached? %>
                </div>
         
                <div class="pl-2"><%=user.username %> </div>
            </div>

          <% end %>
        </div>

app/views/users/show.html.erb
<div class="flex justify-between">
 <%= render partial: 'sidebar' %>

  <div class="flex w-5/6 justify-between main-content">
    <div class="flex w-full">
      <div class="flex-col" style="margin-left: 30%; width:85%;">
        <div class="flex items-center  p-5 mt-20" style="width: 80%;">
          <div class="rounded-full bg-slate-200" style="height: 200px; width:200px; ">
            <%= image_tag @user.profile_photo, class: "h-full w-full rounded-full" if @user.profile_photo.attached? %>
          </div>
          <div class="flex-col ml-20">
            <div class="flex items-center">
              <h1 class="font-bold"><%= @user.username %></h1>
              
              <% if @user.id == current_user.id %>
                <p class="ml-5 rounded bg-slate-200 py-1 px-2 font-bold">
                  <%= link_to "Edit Profile", edit_user_registration_path(@user)%>
                </p>
               <% else %>

                <div class="ml-5 ">
                  <% if current_user.following?(@user) %>
                    <%= button_to "Unfollow", unfollow_connection_path(@user), class:"rounded bg-sky-200 py-1 px-2 font-bold text-sm text-white" %>
                  <% elsif current_user.sent_follow_request_to?(@user)%>
                    <%= button_to "Cancel follow request", cancel_connection_path(@user) , class:"rounded bg-red-200 py-1 px-2 font-bold text-sm text-whit" %>
                  <% else %>
                    <%= button_to "Follow",  follow_connection_path(@user) , class:"rounded bg-sky-200 py-1 px-2 font-bold text-sm text-white" %>
                  <% end %>
                </div>
              <% end %>

            </div>
            <div class="mt-5 flex">
                <%= pluralize(@user.posts.count, 'post') %>
                <p class="ml-5"><%= pluralize(current_user.followers.count, 'follower')%></p>
                <p class="ml-5"><%= pluralize(current_user.following.count, 'following')%></p>
                


            </div>
            <div class="mt-5">
              <h1 class="font-bold"><%= @user.first_name %> <%= @user.last_name %></h1>
              <p class="font-light"><%= @user.bio %></p>
            </div>
          </div>
        </div>
        
          <div class="flex flex-wrap justify-between mt-10" style="width: 850px;">
              <% @posts.each do |post| %> 
                <div class="border mt-2 p-3" style="width:280px; height:300px">
                 <h2 class="font-light text-xs">Author: <%= post.user.username %>:</h2>
                  <p class="font-light text-xs">Created on: <%= post.created_at.strftime("%B %d, %Y") %></p>    
                  <h1 class="font-bold text-sm"><%= post.title %></h1>
                  <p class="font-light text-sm"><%= post.description %></p>
                  <%= image_tag post.photo, class: "h-3/5 w-full"  if post.photo.attached? %>
                </div>
              <% end %>
          </div>
      

      </div>
    </div>
    <div class="w-1/4 justify-self-center text-center mt-20">

    </div>
  </div>
</div>
         
 