config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # resource :cart, only: [:show] do
  #   post 'add', on: :member
  #   post 'remove', on: :member
  # end
  get 'cart', to: 'cart#show'
  post 'cart/add'
  post 'cart/remove'

  
  resources :connections, only: [] do
    member do
      post 'follow', 'unfollow', 'accept', 'decline', 'cancel'
    end
  end

  resources :users, only: [:show] do
    resources :posts, :products
  end

  resources :posts do
    resources :likes, module: :posts, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end

  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :orders
    has_many :products, through: :orders

    def total
        orders.to_a.sum { |order| order.total }
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :record, polymorphic: true, counter_cache: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total
    product.price * quantity
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :photo
  has_many :comments
  has_many :likes, as: :record
  belongs_to :user

  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 10 }

  def like_by?(user)
    likes.where(user:).any?
  end

  def like(user)
    likes.where(user:).first_or_create
  end

  def unlike(user)
    likes.where(user:).destroy_all
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :orders
  has_many :carts, through: :orders

  has_one_attached :image
  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts
  has_many :products
  has_one_attached :profile_photo
  has_many :likes
 
  
  followability

  validates :username, presence: true, uniqueness: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  def unfollow(user)
    followerable_relationships.where(followable_id: user.id).destroy_all
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @render_cart = false
    
  end

  def add
    @product = Product.find_by(id: params[:id])
    quantity = params[:quantity].to_i
    current_order = @cart.orders.find_by(product_id: @product.id)
    if current_order && quantity > 0
      current_order.update(quantity:)
    elsif quantity <= 0
      current_order.destroy
    else
      @cart.orders.create(product: @product, quantity:)

    end



  end

  def remove
    Order.find_by(id: params[:id]).destroy
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace('cart',
                                                  partial: 'cart/cart',
                                                  locals: { cart: @cart })
      end
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: [:create]
  before_action :set_comment, only: [:edit, :update, :destroy]

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to post_path(@post), notice: 'Comment was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # Define edit, update, and destroy actions here if needed

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @welcome = 'Introducing the ExquisiteEvo Boomer - Unleash the Power of Elegance'
  end
end

app/controllers/posts/likes_controller.rb
class Posts::LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def update
    if @post.like_by?(current_user)
      @post.unlike(current_user)
    else
      @post.like(current_user)
    end
  end
private
    def set_post
        @post = Post.find(params[:post_id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_user
  before_action :set_post, only: %i[edit update destroy]
  before_action :authenticate_user!

  def index
    @posts = Post.all
    @users = User.all
    @post = current_user.posts.build
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @other_posts = @user.posts.where.not(id: @post.id)
  end

  def new
    @post = @user.posts.build
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to user_post_path(current_user, @post), notice: 'Post was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to user_post_path(@user, @post), notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:user_id]) if params[:user_id]
  end

  def post_params
    params.require(:post).permit(:title, :description, :photo)
  end

  def set_post
    @post = @user.posts.find(params[:id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_product, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: [:add_to_cart]
  before_action :set_user

  def index
    @products = Product.all
  end

  def show
    @comment = Comment.new
  end

  def new
    @product = @user.products.new
  end

  def create
    @product = @user.products.build(product_params)

    if @product.save
      redirect_to user_product_path(@user, @product), notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully destroyed.'
  end



  private

  def set_product
    @product = Product.find(params[:id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def product_params
    params.require(:product).permit(:title, :description, :price, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
#   before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/connections_helper.rb
module ConnectionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts/likes_helper.rb
module Posts::LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: [@user, @post], url: user_posts_path(@user,@post), local: true) do |form| %>
  <div>
    <%= form.text_field :title,  placeholder:"title", class:"input my-5" %>
  </div>

    <div class="">
      <div class="flex-col">
        <div>
          <%= form.text_area :description, placeholder:"description", class:"input" %>
        </div>
        <div class="my-3">
          <%= form.file_field :photo, class: "custom-file-input" %>
          <%# <%= form.file_field :photo, class: "custom-file-input", id: "customFile" %> 
        </div>
      </div>

      <div>
        <%= form.submit class:"bg-red-300 w-full p-2 text-white text-xs font-bold" %>
      </div>

      <div class="my-5">
        <% @post.errors.full_messages_for(:description).each do |message| %>
          <div class="font-light text-xs text-red-500"><%= message %></div>
      <% end %>
      <% @post.errors.full_messages_for(:title).each do |message| %>
        <div class="font-light text-xs text-red-500"><%= message %></div>
      <% end %>
      </div>
    </div>
<% end %>

app/views/posts/_likes.html.erb
<%= button_to post_like_path(@post), method: :patch do %>
  <%= icon('fa-solid', 'heart', class: 'icon heart px-2') %>
<% end %>

<%= post.likes_count%>

app/views/posts/_post_list.html.erb
<% @posts.each do |post| %>
  <div class="border flex-col p-4 my-5" style="height: 500px; width: 100%;">
    <!-- ... Post content ... -->
  </div>
<% end %>

app/views/posts/_sidebar.html.erb
  <div class=" w-1/6 left-hand-side border-r-2">
      <div class="flex-col h-full justify-between ">
      <div class="mx-10 my-10" style="color: #003049;">
        <%= link_to 'Boomer', posts_path, class:"text-2xl font-bold tracking-widest" %>
      </div>
      <div class="flex-col justify-between h-3/5 mx-10 my-10" style="">
        <div class="h-1/6 flex items-center">
          <%= icon('fa-solid', 'pen-to-square', class: 'icon')%>
          <%= turbo_frame_tag "post_modal" do %>
            <%= link_to "Create", new_user_post_path(current_user), class:"text-sm ml-3" %>
          <% end %>
        </div>
        <div class="h-1/6 flex items-center">
           <%= icon('fa-solid', 'house', class: 'icon')%>
           <%= link_to 'Home', posts_path, class:"text-sm ml-3" %>
        </div>
        <div class="h-1/6 flex items-center">
          <%= icon('fa-solid', 'shop', class: 'icon')%>
          <p class="text-sm ml-3">Sell</p>
        </div>
        <div class="h-1/6 flex items-center">
          <%= icon('fa-solid', 'envelope', class: 'icon')%>
          <p class="text-sm ml-3">Messages</p>
          
        </div>
        <div class="flex h-1/6 items-center">
          <%= icon('fa-solid', 'heart', class: 'icon')%>
          <p class="text-sm ml-3">Notification</p>
        </div>
        <div class="flex h-1/6 items-center">
          <%= image_tag current_user.profile_photo, class: "h-8 w-8 rounded-full" if current_user.profile_photo.attached? %>
          <%= link_to 'Profile', user_path(current_user), class:'text-sm ml-3' %>
        </div>
      </div>
      <div class="w-full text-center p-2 flex justify-around" style="position:absolute; top:95%">
          <%= icon('fa-solid','right-from-bracket', class: 'icon')%>
          <%= button_to "Log Out", destroy_user_session_path, method: :delete, class:"ml-3 font-sm" %>
      </div>
    </div>
  </div>

app/views/posts/_user_list.html.erb
<div class="border p-5 mt-20" style="width: 85%;">
  <div class="flex justify-between items-center" style="width: 25%;">
    <% @users.each do |user| %>
      <% if user.id != current_user.id %>
        <%= link_to user_path(user.id)  do  %>
          <div class="flex-col items-center">
            <div class="rounded-full bg-slate-200 w-16 h-16">
              <%= image_tag user.profile_photo, class: "h-full w-full rounded-full" if user.profile_photo.attached? %>
            </div>
            <div class="text-center text-sm font-light"><%= user.username %></div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<%= turbo_frame_tag "post_modal" do %>
 <div class="modal-overlay"></div>
  <div class="modal flex-col">
    <div class="flex border-b w-full justify-between items-center p-3">
      <div></div>
      <h1 class="font-bold text-sm">Edit Post</h1>
      <%= link_to "X", posts_path, class: "text-center text-slate-700 font-medium focus:ring-4 focus:ring-slate-100 no-underline inline-block", data: { turbo: false } %>
    </div>
      
      <div class="mt-10">
        <%= form_with(model: [@user, @post], url: user_post_path(@user,@post), local: true) do |form| %>
            <div>
              <%= form.text_field :title,  placeholder:"title", class:"input my-5" %>
            </div>
            <div class="">
              <div class="flex-col">
                <div>
                    <%= form.text_area :description, placeholder:"description", class:"input" %>
                </div>
                <div class="my-3">
                    <%= form.file_field :photo, class: "custom-file-input" %>
                <%# <%= form.file_field :photo, class: "custom-file-input", id: "customFile" %> 
                </div>
              </div>
              <div>
                <%= form.submit class:"bg-red-300 w-full p-2 text-white text-xs font-bold" %>
              </div>
              <div class="my-5">
                <% @post.errors.full_messages_for(:description).each do |message| %>
                    <div class="font-light text-xs text-red-500"><%= message %></div>
                <% end %>
                <% @post.errors.full_messages_for(:title).each do |message| %>
                    <div class="font-light text-xs text-red-500"><%= message %></div>
                <% end %>
             </div>
            </div>
        <% end %>
      </div>
  </div>
<% end %>

app/views/posts/index.html.erb
<div class="flex justify-between items-center">
  <%= render partial: 'sidebar' %>

  <div class="flex w-5/6 justify-between">
    <div class="flex w-full">
      <div class="flex-col" style="margin-left: 30%;">
      <div class="border p-5 mt-20" style="width: 85%;">
        <div class="flex justify-between items-center " style="width: 25%;">
         <% @users.each do |user| %>
            <% if user.id != current_user.id %>
                <%= link_to user_path(user.id)  do  %>
                  <div class="flex-col items-center">
                      <% if current_user.following?(user) %>
                        <div class="rounded-full bg-slate-200 w-16 h-16">
                          <%= image_tag user.profile_photo, class: "h-full w-full rounded-full" if user.profile_photo.attached? %>
                        </div>
                        <div class="text-center text-sm font-light"><%=user.username %></div>
                      <% end %>
                  </div>
                <%end%>
            <% end %>
         <%end%>
        </div>
      </div>
    

        
        <div class="flex-col" style="margin-top:10%; width:85%;">
          <% @posts.each do |post| %>
            <div class="flex justify-between items-center">
              <%= link_to user_path(post.user), class:'text-sm ml-3' do %>
                <div class="flex items-center">
                    <div class="rounded-full bg-slate-200 h-14 w-14">
                      <%= image_tag post.user.profile_photo, class: "h-14 w-14 rounded-full" if post.user.profile_photo.attached? %>
                    </div>
                  <div class="pl-2">
                    <%=post.user.username %> 
                  </div>
                </div>
              <% end %>
                <div>
                  <%= turbo_frame_tag "post_modal" do %>
                    <a href="/posts/<%= post.id %>">
                    <%= icon('fa-solid', 'ellipsis', class: 'icon')%>
                    </a>
                  <% end %>
                </div>
            </div>
  
            <div class="border flex-col p-5 my-5" style="height: 100%; width:100%;">
              <div class="">
                <%= image_tag post.photo,class: "post-image  object-fill"  if post.photo.attached? %>
              </div>

              <div class="reactions">
                <a class="flex items-center justify-between" href="/posts/<%= post.id %>">
                  <%= icon('fa-solid', 'comment', class: 'icon px-1')%>
                  <p class="text-xs font-light px-2"><%= post.comments.count %></p>
                  <%# <%= render partial:"likes", locals: {post: post} %> 

                </a>
                <div class="flex items-center">
                    <%= icon('fa-solid', 'heart', class: 'icon heart px-2') %>
                 
             
                  <p class="text-xs">
                     <%= post.likes_count%>
                  </p>
                 
                </div>
           

              </div>

              <div class="mt-2">
                <h1 class="font-bold text-sm"><%= post.title %></h1>
                <p class="font-light text-sm"><%= post.description %></p>
              </div>
              
            </div>
          <% end %>
        </div>
      

      </div>
    </div>
    <div class="w-1/4 text-center mt-20">
      <div class="flex items-center justify-between">
        <div class="flex items-center">
          <%= link_to user_path(current_user) do %>
            <div class="rounded-full bg-slate-200 w-12 h-12">
              <%= image_tag current_user.profile_photo, class: "h-full w-full rounded-full" if current_user.profile_photo.attached? %>
            </div>
          <% end %>
          <div class="pl-2 text-sm font-bold"><%=current_user.username %> </div>
        </div>
        <div></div>
      </div>

      <div class="flex-col p-2 border justify-around mt-10" style="width: 90%; height:10%">
         <div class="flex justify-between"  style="width: 95%; margin-left:2.5%">
          <h1 class="text-sm text-slate-500">suggested for you</h1>
          <p class="text-sm font-bold">View all</p>
         </div>
         
         <div style="width: 98%;">
            <% @users.each do |user| %>
              <% if user.id != current_user.id && !current_user.following?(user) %>
                <div class="flex items-center justify-between mt-5" style="width: 98%; margin-right:1%">
                  <div class="flex items-center">
                    <div class="rounded-full bg-slate-200 w-12 h-12 ml-4">
                      <%= image_tag user.profile_photo, class: "h-full w-full rounded-full" if user.profile_photo.attached? %>
                    </div>
                    <div class="text-sm font-bold pl-2"><%=user.username %></div>
                  </div>
                    <%= button_to "Follow",  follow_connection_path(user), class:"bg-green-300 text-white font-light text-xs rounded w-16 h-8 p-1" %>
                </div>
              <% end %>
            <% end %>
         </div>
         
      </div>
      
      <div class="flex-col p-2 border justify-around mt-10" style="width: 90%; height:10%">
         <div class="flex justify-between"  style="width: 95%; margin-right:2.5%">
          <h1 class="text-sm text-slate-500">Friends you follow</h1>
          <p class="text-sm font-bold">View all</p>
         </div>
         
         <div style="width: 98%;">
              <% current_user.followers.each do |user| %>
                <div class="flex items-center justify-between mt-5" style="width: 98%; margin-right:1%">
                  <div class="flex items-center">
                    <div class="rounded-full bg-slate-200 w-12 h-12 ml-4">
                      <%= image_tag user.profile_photo, class: "h-full w-full rounded-full" if user.profile_photo.attached? %>
                    </div>
                    <div class="text-sm font-bold pl-2"><%=user.username %></div>
                  </div>
                    <%= button_to "Unfollow",  unfollow_connection_path(user), class:"bg-red-300 text-white font-light text-xs rounded w-16 h-8 p-1" %>
                </div>
              <% end %>
         </div>
         
      </div>




  
    <% current_user.follow_requests.each do |request| %>
      <div class="border mt-10 w-3/4 p-3 flex-col ml-12">
        <div class="flex items-center">
          <%= image_tag request.followerable.profile_photo, class: "h-12 w-12 rounded-full" if request.followerable.profile_photo.attached? %>
          <p class="text-xs font-light text-left"><strong><%= request.followerable.username %></strong> wants to follow you</p>
        </div>
        <div class="flex items-center mt-2">
          <%= button_to "Accept", accept_connection_path(request.followerable), class:"bg-green-300 text-white font-light font-xs rounded w-16 h-8 p-1" %>
          <%= button_to "Decline", decline_connection_path(request.followerable), class:"bg-red-300 text-white font-light fonts-xs rounded w-16 h-8 p-1 ml-4" %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<%= turbo_frame_tag "post_modal" do %>
 <div class="modal-overlay"></div>
  <div class="modal flex-col">
    <div class="flex border-b w-full justify-between items-center p-3">
      <div></div>
      <h1 class="font-bold text-sm">New Post</h1>
      <%= link_to "X", posts_path, class: "text-center text-slate-700 font-medium focus:ring-4 focus:ring-slate-100 no-underline inline-block", data: { turbo: false } %>
    </div>
      
      <div class="mt-10">
        <%= render "form", post: @post %>
      </div>
  </div>
<% end %>

app/views/posts/show.html.erb
<%= turbo_page_requires_reload %>
<div class="flex justify-between ">
 <%= render partial: 'sidebar' %>
  <div class="flex w-5/6 justify-between main-content">
        <div class="flex-col mt-20" style="margin-left: 25%; height: 47%; width:100%;">
          <div class="flex" style=" height: 100%; width:100%;">
              <div class="border p-4 " style="width:500px" >
                <div class="">
                  <%= image_tag @post.photo, class:"showpost" if @post.photo.attached?  %>
                </div>
                <h1 class="text-sm font-bold"><%= @post.title %></h1>
                <p class="text-sm font-light"><%= @post.description %></p>
              </div>
              <div class="border" style="width:350px; height:92%">
              <div class="flex justify-between items-center border-b p-1">
                <div class="flex items-center ">
                  <%= image_tag @user.profile_photo, class: "w-9 h-9 rounded-full" if @user.profile_photo.attached? %>
                  <span class="text-sm font-bold ml-2"><%= @user.username %></span>
                </div>
                
                <% if @user.id == current_user.id %>
                  <%= turbo_frame_tag "post_modal" do %>
                    <%= link_to edit_user_post_path(user_id: @post.user, id: @post) do %>
                        <%= icon('fa-solid', 'ellipsis', class: 'icon')%>
                    <%end%>
                  <%end%>
                <% end %>
                

              </div>
              
               <div class="comment">
                  <div>
                     <%= render @post.comments %>
                  </div>
                  <div>
                    <%= render 'comments/form', post: @post %>
                  </div>
               </div>

              </div>
          </div>

          <div class="mt-10 border-b" style="width: 850px;"></div>
          <div class="mt-10 text-2xl"> <h2>Other Posts by <%= @user.username %>:</h2></div>
          <%= render partial:"likes", locals: {post: @post} %>
      <% if @other_posts.any? %>
          <div class="flex flex-wrap justify-between mt-20" style="width: 850px; height:100%;">
              <% @other_posts.each do |other_post| %> 
              <a href="/posts/<%= other_post.id %>">
                <div class="border" style="width:280px; height:300px">
                 <h2 class="font-bold text-xs"><%= other_post.user.username %>:</h2>
                  <p class="font-light text-xs">Created on: <%= @post.created_at.strftime("%B %d, %Y") %></p>    
                  <h1 class="font-bold text-sm"><%= other_post.title %></h1>
                  <p class="font-light text-sm"><%= other_post.description %></p>
                  <%= image_tag other_post.photo, class: "h-3/5 w-full"  if other_post.photo.attached? %>
                </div>
              </a>
              <% end %>
          </div>
      <% else %>
          <p>No other posts from <%= @user.username %> yet.</p>
      <% end %>
        </div>


      <div class="w-1/4 justify-self-center text-center">
        <p class="text-xs font-light text-slate-300">Posted by: <%= link_to @user.username, user_path(@user) %></p>
        <p class="text-xs font-light text-slate-300">Posted on: <%= @post.created_at.strftime("%B %d, %Y") %></p>
      </div>
  </div>
</div>